In [70]:
np.random.exponential(1, size = 2)

array([0.6938116 , 0.06584302])

In [68]:
np.random.poisson(6.0, size = 5*2).reshape(5,2)

array([[11,  7],
       [ 5,  5],
       [ 7,  9],
       [ 1,  7],
       [10,  4]])

In [ ]:
np.apply_along_axis(f, axis = 1, a)   #применить функцию f к массиву a

In [16]:
nz = np.nonzero([1,2,0,0,4,0]) #индексы ненулевых элементов массива
print(nz)

(array([0, 0, 1, 1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))


In [29]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)  #оборачивает массив в рамку
print(Z)

[[5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 1. 1. 1. 1. 1. 5. 5.]
 [5. 5. 1. 1. 1. 1. 1. 5. 5.]
 [5. 5. 1. 1. 1. 1. 1. 5. 5.]
 [5. 5. 1. 1. 1. 1. 1. 5. 5.]
 [5. 5. 1. 1. 1. 1. 1. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5.]]


In [ ]:
Z = np.diag(1+np.arange(4),k= -1) #строим матрицу, по k диагонали у которой массив 1+np.arange(4)
Z

In [ ]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1 #создаем шахамтную матрицу из 1, 0
Z

In [ ]:
#функция tile повторяет массив
Z = np.tile( np.array([[0,1],[1,0]]), (4,4)) #создаем шахамтную матрицу из 1, 0
Z 

In [3]:
import pandas as pd
path = input()
df = pd.read_csv(path, sep='\t')
df = df[df.male_dummy == 1]
df['res'] = df['instagram_dummy'] + df['twitter_dummy']
df = df[df.res == 1]
print(df.shape[0])
print(df)

test_data.csv
18
            city country first_name                 home_town    last_name  \
2         Москва  Россия      Стёпа                       NaN      Севагин   
3         Москва  Россия       Иван                       NaN     Чумачков   
5         Москва  Россия      Аббос                       NaN       Одилов   
42        Москва  Россия   Владимир                 Тирасполь  Загниборода   
59        Москва  Россия      Борис                       NaN      Кудинов   
60        Москва  Россия      Vanya                       NaN       Fateev   
77           NaN     NaN     Кубрат                       NaN     Мингазов   
111       Москва  Россия     Андрей           Ростове-на-Дону     Бережной   
114          NaN     NaN    Марсель                       NaN    Франкфурт   
154          NaN  Россия      Тимур                       Уфа      Манапов   
157  Новосибирск  Россия     Кирилл  Саяногорск,Бердск,Москва    Емельянов   
195       Москва  Россия       Саша            

In [4]:
import pandas as pd
name = input()
df = pd.read_csv('{}'.format(name), sep='\t')
df.sort_values(by=['followers_cnt'])
df

test_data.csv


city country first_name     home_town  last_name  \
0    Екатеринбург  Россия      Данил  Екатеринбург  Отдельнов   
1          Москва  Россия      Мария        Москва  Сметанина   
2          Москва  Россия      Стёпа           NaN    Севагин   
3          Москва  Россия       Иван           NaN   Чумачков   
4          Москва  Россия  Anastasia           NaN  Biryukova   
..            ...     ...        ...           ...        ...   
271           NaN  Россия       Анна           NaN     Адамян   
272        Москва  Россия    Николай           NaN  Дементьев   
273        Москва  Россия  Anastasia           NaN  Natrusova   
274           NaN     NaN     Никита           NaN    Карабиц   
275           NaN     NaN      Борис    lauderhill    Метелёв   

     in_hse_memes_group  wall_repost_cnt  wall_like_mean political_cat  \
0                 False            182.0        1.881428           NaN   
1                  True              NaN             NaN           NaN   
2                 False              0.0       25.285714           NaN   
3                 False              2.0        5.217391           NaN   
4                  True              0.0       21.333333           NaN   
..                  ...              ...             ...           ...   
271                True              NaN             NaN           NaN   
272                True              NaN             NaN           NaN   
273                True              4.0       28.594142           NaN   
274                True              NaN             NaN           NaN   
275               False              0.0        3.000000           NaN   

     subscriptions_cnt  instagram_dummy  skype_dummy  twitter_dummy  \
0                 14.0                0            1              0   
1                  0.0                0            0              0   
2                  0.0                1            0              0   
3                  4.0                1            0              0   
4                  0.0                1            1              0   
..                 ...              ...          ...            ...   
271                0.0                0            0              0   
272               65.0                0            0              0   
273                2.0                0            0              0   
274                0.0                0            0              0   
275                4.0                0            0              0   

     male_dummy  followers_cnt  
0             1          110.0  
1             0           32.0  
2             1          177.0  
3             1          166.0  
4             0          340.0  
..          ...            ...  
271           0          283.0  
272           1            NaN  
273           0          185.0  
274           1            NaN  
275           1           21.0  

[276 rows x 15 columns]

In [6]:
import pandas as pd
path = input()
df = pd.read_csv(path, sep='\t')
df = df[df.male_dummy == 1]
print(len(df[(df.twitter_dummy == 1) | (df.instagram_dummy == 1)]))
df = df[(df.twitter_dummy == 1) | (df.instagram_dummy == 1)]
print(df)

test_data.csv
21
            city country first_name                 home_town    last_name  \
2         Москва  Россия      Стёпа                       NaN      Севагин   
3         Москва  Россия       Иван                       NaN     Чумачков   
5         Москва  Россия      Аббос                       NaN       Одилов   
24        Москва  Россия     Андрей                       NaN     Гладышев   
42        Москва  Россия   Владимир                 Тирасполь  Загниборода   
59        Москва  Россия      Борис                       NaN      Кудинов   
60        Москва  Россия      Vanya                       NaN       Fateev   
77           NaN     NaN     Кубрат                       NaN     Мингазов   
111       Москва  Россия     Андрей           Ростове-на-Дону     Бережной   
114          NaN     NaN    Марсель                       NaN    Франкфурт   
154          NaN  Россия      Тимур                       Уфа      Манапов   
157  Новосибирск  Россия     Кирилл  Саяногорск

In [ ]:
import pandas as pd
name = input()
df = pd.read_csv('{}'.format(name), sep='\t')
df = df[df.male_dummy == 1]
df['res'] = df['instagram_dummy'] + df['twitter_dummy']
df = df[df.res != 0]
print(df.shape[0])

In [ ]:
#df['res1'] = df['male_dummy'] * df['instagram_dummy'] + df['male_dummy'] * df['twitter_dummy']
df = df[df.male_dummy == 1]
df['res'] = df['instagram_dummy'] + df['twitter_dummy']
df = df[df.res != 0]
print(df.shape[0])

In [ ]:
#PANDAS

In [ ]:
#SERIES

import pandas as pd
my_series = pd.Series([5, 6, 7, 8, 9, 10]) #по умолчанию индексы от 0 до n
my_series2 = pd.Series([5, 6, 7, 8, 9, 10], index=['a', 'b', 'c', 'd', 'e', 'f'])
my_series3 = pd.Series({'a': 5, 'b': 6, 'c': 7, 'd': 8})
my_series3.index = ['A', 'B', 'C', 'D'] #в любой момент можно поменять индексы
my_series.index #вытаскивает индекс(ключи)
my_series.values #вытаскивает занчения
my_series[4] #вытаскивает значение под индексом 4
my_series2['f']  #вытаскивает значение под индексом f 
my_series2[my_series2 > 0] * 2 #вытаскивает удвоенные значения, которые больше 0
my_series2[['a', 'b', 'f']] = 0  #присваивание к нулю значений под индексами  a, b, f


In [ ]:
#DataFrame
df = pd.read_csv('filename.csv', sep=',')
df = pd.DataFrame({
     'country': ['Kazakhstan', 'Russia', 'Belarus', 'Ukraine'],
     'population': [17.04, 143.5, 9.5, 45.5],
     'square': [2724902, 17125191, 207600, 603628]}) #индексы по умолчаниб от 0 до n

df.index = ['KZ', 'RU', 'BY', 'UA'] #в любой момент можно поменять индексы
df.reset_index() #сброс индексов, по умолчанию от 0 до n
df.info()
df.shape  #размер таблицы
df.head(n) #первые n строк таблицы
df.tail(n)
df.columns #назвния колонок списком
df = df.rename(columns={'Country Code': 'country_code'}) #переименовать столбец


df.sort_values(by='Total day charge', ascending=False) #сортировка по столбцу

df.loc['KZ'] #данные из строки с индексом KZ
df.iloc[0] #данные из строки с индексом 0
df['country'] #данные по столбцу country
df.loc[['KZ', 'RU'], 'population'] #данные их строк с индексом KZ, RU по столбцу population
df.loc['KZ':'BY', :]
df[df.population > 10][['country', 'square']] #берем только с population >10, выводим столбцы country, square


df['Age'].value_counts()  #Выведем уникальные значения по возрасту и сколько раз каждое из них встречается
df["Club"].unique() #вывести уникальные значения в столбце "Club"
df["Club"].nunique() #посчитать колво уникальных значений в столбце "Club"


df["Wage"].mean() #среднее арифм значений столбца "Wave"
df.isnull().sum() #количество пустот в каждом столбце (тип данных series)
(df["Age"] == 31).sum()
df[df["Age"] == 31]["Wage"].mean()
.count()  #выводит количество

df['density'] = df['population'] / df['square'] * 1000000   #добавим новый столбец density
df.drop(['density'], axis='columns')  #удалим столбец density


#Добавляет колонку Total calls в столбец номер loc таблицы
total_calls = df['Total day calls'] + df['Total eve calls'] + df['Total night calls'] + df['Total intl calls']
df.insert(loc=len(df.columns), column='Total calls', value=total_calls)

#GroupBy
titanic_df.groupby(['Sex', 'Survived'])['PassengerID'].count()  #выводит количество участников из группы в зависмости от sex и survived


#СВОДНЫЕ ТАБЛИЦЫ
titanic_df = pd.read_csv('titanic.csv')  #базовая таблица
# создает сводную, индексами будет пол, столбцами PClass, занчениями внутри таблицы количество 
pvt = titanic_df.pivot_table(index=['Sex'], columns=['PClass'], values='Name', aggfunc='count')
pvt.loc['female', ['1st', '2nd', '3rd']] #берет по строке female значения из всех классов

#АНАЛИЗ ВРЕМЕННЫХ РЯДОВ
df['Date'] = pd.to_datetime(df["Date"]) #преобразовываем массив даты в тип 2020-05-15
df.loc['2012-Feb':'2015-Feb', 'Close'].mean() #среднее по строкам даты и столбцу Close
df.resample('W')['Close'].mean()  #среднее значение из столбца Close по каждой Week (H- hour, D - Day)




In [ ]:
#ВИЗУАЛИЗАЦИЯ

In [ ]:
import matplotlib.pyplot as plt
fig, ax = plt.subplots()

ax.plot(['Sep', 'Oct', 'Nov'], [1, 8, 10], color = 'b', marker = 'o', linestyle = '--')
ax.plot(['Sep', 'Oct', 'Nov'], [3, 5, 0], color = 'r', marker = 'v', linestyle = '--')

# Customize the x-axis label
ax.set_xlabel("Time (months)")
# Customize the y-axis label
ax.set_ylabel("Precipitation (inches)")
# Add the title
ax.set_title("Weather patterns in Austin and Seattle")

plt.show()

In [ ]:
import matplotlib.pyplot as plt
listik.plot()  #строит линейный график таблицы с 1 столбцом listik

In [ ]:
fig, ax = plt.subplots()
ax.bar(['Винни-Пух', 'Пятачок', 'Кролик', 'Иа-Иа'], win_num, color = 'g')
ax.set_xticklabels(['Винни-Пух', 'Пятачок', 'Кролик', 'Иа-Иа'], rotation = 90)
ax.set_ylabel("Количество побед")
ax.set_title("Количество побед в марафонах", color = 'g')

plt.show()

In [ ]:
# Create a Figure and an array of subplots with 2 rows and 2 columns
fig, ax = plt.subplots(2, 2)

# Addressing the top left Axes as index 0, 0, plot month and Seattle precipitation
ax[0, 0].plot(seattle_weather["MONTH"], seattle_weather['MLY-PRCP-NORMAL'])

# In the top right (index 0,1), plot month and Seattle temperatures
ax[0, 1].plot(seattle_weather["MONTH"], seattle_weather['MLY-TAVG-NORMAL'])

# In the bottom left (1, 0) plot month and Austin precipitations
ax[1,0].plot(austin_weather["MONTH"], austin_weather['MLY-PRCP-NORMAL'])

# In the bottom right (1, 1) plot month and Austin temperatures
ax[1, 1].plot(austin_weather["MONTH"], austin_weather['MLY-TAVG-NORMAL'])
plt.show()

In [ ]:
import pandas as pd
name = str(input())
зкште()

In [ ]:
import math
from math import factorial
factorial(5)

import random
import pandas as pd  # работа с табличками

import numpy as np  # математика с массивами
from numpy import mean, var
"создает именно матрицу, а не массив массиовов"
matrix = [[1,2,3], [4,5,6],[8,7,9]]
matrix = np.array(matrix)
"количество уровней списков (список списка)"
matrix.ndim
"создает нулевую матрицу 4*4 с единичками в диагонали k"
np.eye(4, k = 0)
"создает нулевую матрицу 3*3*3"
np.zeros((3,3,3))
"создает массив от start включительно до end НЕ включительно с шагом step (может принимать дробные значения)"
np.arange(start, end, step)
"создает массив от start включительно до end включительно из N чисел (может принимать дробные значения)"
np.linspace(start, end, N)
"взятие всех элементов матрицы Х по модулю"
np.abs(X)
"создание списка их элементов матрицы Х по диагонали"
np.diag(X)
"сумма элементов массива"
np.sum(X)
"произведение всех элементов матрицы/списка Х"
np.prod(X)
"поменять форму матрицы Х, сделать (n, m) - количество строк и столбцов"
np.reshape(X, (n, m))
X = X[np.newaxis, :]
X = X[:, np.newaxis]
" выдает (n, m, ...) - количество строк и столбцов, количество элементов в элеменет матрицы и тд, матрицы X"
X.shape
"транспонировать массив"
X.transpose()
"склеивает массивы a, b, c по оси k (по умолчанию k = 0)"
np.concatenate((a, b, c), axis = k)
"наодит среднее значение в массиве а по оси k"
a.mean(axis=k)
"находит вариацию в массиве а по оси k"
a.var(axis=k)
"находит минимальные и максимальные значения в массиве по оси k"
a.min(axis=k)
a.max(axis=k)
"находит индекс минимального и максимального значения(если значение макс или мин несколько, то выдает 0) в массиве по оси k"
a.argmin(axis=k)
a.argmax(axis=k)
import seaborn as sns  # графики
from scipy import special  # спец функции
from scipy.stats import norm, expon, poisson, uniform

a = int(input())
"ввод элементов в список"
a = list(map(int, input().split()))
"ввод из файла"
Fin = open ( "input.txt", "r" )
lst=[int(i) for i in fin.read().split()]
Fout = open ( "output.txt", "w" )
  # работа с файлами
Fout.close()
Fin.close()
"функция ввода до нуля"
def input_(v_list):
    ver = int(input())
    if ver != 0:
        v_list.append(ver)
        input_(v_list)
    return v_list


"строки"
n = str(n) "преобразование в строку"
S1 + S2
S1 * 3
S[i]
S[i:j:step]
len(S)
S.find(str, [start],[end])
S.rfind(str, [start],[end])
S.index(str, [start],[end])
S.replace(шаблон, замена)
S.split(символ)
S.count(str, [start],[end])

"списки"
list.append(x)
list.remove(x) "удаляет первый наденный икс"
list.pop([i]) "удаляет итый элемент"
list.index(x, [start [, end]]) "положение первого элемента икс"
list.count(x)
"сортировка по номеру элемента списка, по возрастанию"
b.sort(key=lambda x: x[0])
list.reverse() "разворачивает"
list[START:STOP:STEP] "START включительно, а STOP не включительно"
list[::-1] "развернет список"
answer = max(list)
sum(list) "сумма элементов списка"

"множества"
s = set()
s = set('hello')
s = {i ** 2 for i in range(10)} # генератор множеств
set(lst) "преобразование списка во множество"
len(s)
x in s
set == other " все элементы set принадлежат other, все элементы other принадлежат set
set <= other " все элементы set принадлежат other
set | other   " объединение нескольких множеств
set & other   "  пересечение
set - other   " множество из всех элементов set, не принадлежащие ни одному из other
set ^ other   " множество из элементов, встречающихся в одном множестве, но не встречающиеся в обоих
set.add(elem)
set.remove(elem)

x // y "целая часть от деления"
x % y "остаок от деления"
abs(a - b) "модуль"

"округление float (6 занков после запятой)"
round(x, 6)

"значения списка поэлементно"
print(*list)
"узнать тип данных"
print(type())
"следующий принт будет на этой строчке через пробел"
print(i, end=' ')
"элементы будут печататься с пробелом"
print("hello,", "world!", sep=' ')
"писать строчку 100 раз"
print('A'*100)

"забываю"
quit()
break

